name: Build and Run Go Program

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: hostname
      run: hostname
    - name: Deploy to server 2
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SERVER_2_HOST: ${{ secrets.SERVER_2_HOST }}

      run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan $SSH_HOST >> /home/runner/.ssh/known_hosts
          echo "$SSH_PRIVATE_KEY" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
          ssh-add /home/runner/.ssh/github_actions
          ssh $SSH_USERNAME@$SSH_HOST "echo 'Hello from GitHub Actions'"